version: '3.9'
services:
  api:
    build: .
    ports:
      - '3030:3030'
    environment:
      MONGODB_URI: 'mongodb://mongo/gazin'
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27018:27018'
